### ISSUE TITLE
Please add Model3D support

### ISSUE THREAD

**Issue by bztsrc** [pegvin/goxel2#12]
Could you please add [this](https://github.com/guillaumechereau/goxel/pull/235) PR to your repo? I'd be great because I saw you provide Linux binaries too!

I've offered guillaumechereau some help in return for merging the PR, but all I got crickets... He just closed the PR without even giving me an answer...

For the records, I can offer the same help to you too, however I see you did a great job on fixing most of the annoying Goxel bugs already! Well done! Also reading your readme made it clear that you've located the most pressing issues with Goxel perfectly. I'm glad that you have forked it, it is definitely in better hands now.

Cheers,
bzt

**Comment by pegvin** [comment]
hey there, thanks! i am looking into it.

**Comment by pegvin** [comment]
Hey there! since i'm a school going guy i don't get much time, but since tomorrow is my day off i'll take a deeper look into model3d and maybe i'll just use model3d as primary export format in replacement of gox format.

I've added your PR for model3d export support, if possible make a PR for model3d import or i'll do it myself in few days & a new release will roll out after this.

**Comment by bztsrc** [comment]
> I've added your PR for model3d export support, if possible make a PR for model3d import.

Thank you! Sadly I cannot create new PRs since the latest modifications on github. But I see there's no need, you have already merged that!

Import is a bit more complex issue, because .m3d files can store a lot more than voxel images, and even for voxel images there are a lots of options to make the storage efficient. I'll think about it, I'll let you know if I have a working prototype! Maybe I should add m3d.h too and rewrite the export using that single file SDK, that would simplify things considerably.

Thank you again!
bzt

**Comment by pegvin** [comment]
I'll try to figure out stuff myself till then cause I'm really interested in model3d format.

The gox format took few kilobytes to store a model and m3d took few hundred bytes.

**Comment by bztsrc** [comment]
> I'll try to figure out stuff myself till then cause I'm really interested in model3d format.

If that's the case then I'll definitely add import too using the M3D SDK. Until then, [here](https://gitlab.com/bztsrc/model3d/-/blob/master/docs/voxel_format.md) is a simplified description of the format for voxel images only. At the bottom there's a [short description](https://gitlab.com/bztsrc/model3d/-/blob/master/docs/voxel_format.md#using-the-m3d-sdk-with-voxel-images) on how to use the M3D SDK to read and store voxel images specifically.

But I'll work on this, it's just right now I'm busy with other projects, so I'd like to ask for you patience.

> The gox format took few kilobytes to store a model and m3d took few hundred bytes.

Yep, they both use the same compression, but gox stores multiple, separately compressed PNGs of fixed sized blocks, each with its own header overhead, while m3d measures the bounding box, uses flexible layout and the smallest index size possible and compresses everything in one run (first with RLE, then with zlib). If interested, the fully blown spec is [here](https://gitlab.com/bztsrc/model3d/blob/master/docs/m3d_format.md#voxel-face) (with materials, named voxel types etc.).

But the SDK has a pretty simple and straightforward API, so you don't have to care about the details. FYI, rotation info and voxel shapes are not handled by the SDK yet, but that's irrelevant because goxel itself can handle cube shaped voxels only.

Cheers,
bzt
