### ISSUE TITLE
Texture Export For obj

### ISSUE THREAD

**Issue by Merlin1846** [pegvin/goxel2#34]
I have searched every where and the only Voxel modeler for Linux that has bit the dust is Goxel but sadly I can not for the life of me get my texture exported.

Export the texture, please, even a png would do.

**Comment by Merlin1846** [comment]
I've checked the main Goxel but there seems to be some kind of aversion to this.

**Comment by pegvin** [comment]
Hey There @Merlin1846, I'm Really Sorry But I have alot of stuff to handle and my 3d graphics programming skills aren't that good so this project isn't really maintained. Making a PR On Original Project's GitHub Repo Might Work.

**Comment by pegvin** [comment]
After This PR Is Closed I'll All Together Close Issues Section.

**Comment by Merlin1846** [comment]
Ok, I think I found a way to paint the uvs in Blender anyways.
