### ISSUE TITLE
Backport changes from betterspades fork?

### ISSUE THREAD

**Issue by poVoq** [pegvin/goxel2#5]
https://github.com/xtreme8000/goxel

Has some nice additions to better support Ace of Spades and similar games.

Would be nice if you could back-port them to this fork.

**Comment by pegvin** [comment]
Hi there, interesting changes you've made there.

**Comment by pegvin** [comment]
Seems like i'll need mac to fix stuff, give me some time.

**Comment by poVoq** [comment]
see also:
https://github.com/xtreme8000/goxel/issues/2

Might be helpful as well.
